* Simplified Formula
** Hitting
5% of the time, a hit or miss will occur regardless of to-hit or EV.

EV is doubled, rolled twice, and averaged. To-hit is rolled.

If to-hit is higher than EV, the attack hits.

Thus, EV tends to be smaller than to-hit, and a point of EV is more effective than a point of to-hit.
*** Player attacks Monster
**** Player to-hit
Sum of the following:

+ Base value of 15
+ Dexterity / 2 (exact)
+ Fighting skill / 2 (rolled)
+ Relevant weapon skill / 2 (rolled)
+ Weapon's base accuracy
+ Weapon's enchantment level
+ Slaying bonuses
+ Other modifiers
**** Monster Evasion (EV)
Monster EV is basic value based on the monster type.

Orc EVs are around 10; exact value depends on type.
*** Monster attacks Player
**** Monster to-hit
Sum of the following:

+ Base value of 18
+ Monster HD * 1.5 (or 2.5 if monster tagged Fighter)
+ Other modifiers
**** Player Evasion (EV)
Sum of the following:

+ Base value of 10
+ Size factor (large players are easier to hit)
+ Roughly: Dodging * Dexterity * (Str / Encumbrance)
+ Roughly subtract: (Encumbrance^2 - Armour Skill) / Str
+ Roughly subtract: Shield Encumbrance - Shield Skill
+ Other modifiers

"Roughly" means I've left out scaling factors. Fortunately, the game calculates EV for us and shows us the result.

The important thing is the relation between the factors, such as:
+ Dodging and Dexterity multiply.
+ Str and Amour Skill help with Encumbrance.
+ Encumbrance is squared at one point.

This is one of the most complicated formulas in the game.
** Damage
Damage is rolled and AC is rolled. Rolled damage is reduced by rolled AC.

Rolled AC also reduces magic damage.
*** Player attacks Monster

**** Player damage
Product of the following:

+ Weapon base damage
+ 0.75 + 0.025 * Str (equals 1.0 at Str 10)
+ 1 + Weapon Skill / 25
+ 1 + Fighting Skill / 30

Plus bonuses:
+ Might or Berserk: +1d10 (1 to 10)
+ Weapon enchantment level
+ Slaying bonuses
+ Other bonuses

Finally:
+ Stabbing bonus multipliers
+ Axes (and other cleaving attacks) are multiplied by 0.7.
**** Monster AC
Monster AC is basic value based on the monster type.

Unarmoured Orcs have an AC around 2; exact value depends on type.
Armoured Orcs have an AC around 10; exact value depends on type.
*** Monster attacks Player
**** Monster damage
Monsters have defined attack damage and sometimes random weapons.
**** Player AC
Mostly comes from worn armour. The game is pretty clear about AC effects.

AC has a guaranteed melee damage reduction (GDR). At 40 AC, melee damage will be reduced 40%. GDR follows a root scale (1/4).
** Weapon Speed
Weapon speed may be reduced by the relevant weapon skill. The game is clear about these numbers in weapon descriptions.
